### ISSUE TITLE
TimePicker onSubmit function return

### ISSUE THREAD

**Issue by HasanBS** [koukibadr/Bottom-Picker#13] opened 2021-08-15 11:14 UTC
For the time picker, onSubmit function always return Datetime.now(), _renderDateTimePicker function need to update selectedDateTime 

```
 Container _renderDateTimePicker(CupertinoDatePickerMode mode) {
    return Container(
      height: 200,
      child: CupertinoDatePicker(
          mode: mode,
          onDateTimeChanged: (DateTime date) {
            this.selectedDateTime = date; // That part is missing
            this.widget.onChange?.call(date);
          },
          initialDateTime: this.widget.initialDateTime,
          maximumDate: this.widget.maxDateTime,
          minimumDate: this.widget.minDateTime,
          use24hFormat: this.widget.use24hFormat),
    );
  }

```

**Comment by koukibadr** [comment] 2021-08-15 14:29
Okay @HasanBS  I will check it and fix it 
I'll let you know about the new fixes

**Comment by koukibadr** [comment] 2021-08-15 14:36
Thanks a lot @HasanBS  the problem is fixed now 
I will publish a new version of  the package

**Closed** 2021-08-15 14:36 UTC
